In [1]:
import pandas as pd
import glob

In [2]:
csv_files = glob.glob(r'G:\Mohanraj D_OFFICIAL\GUVI (Data Analyst)\Mini-Projects\PatrolIQ\*.csv')     # This will create a list of path of each csv file present in my PatrolIQ folder 

list_df = []                                                  # An empty list to store all dataframes
for file in csv_files:
    read = pd.read_csv(file)
    list_df.append(read)

df = pd.concat(list_df, ignore_index=True)                    # create one dataframe

In [3]:
pd.set_option("display.max_columns", None)

In [4]:
df.shape

(2997481, 22)

In [5]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [6]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10819224,JA119772,12/31/2016 11:59:00 PM,100XX W OHARE ST,0810,THEFT,OVER $500,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,False,False,1651,16.0,41.0,76.0,06,1100658.0,1934241.0,2016,02/10/2018 03:50:01 PM,41.976290,-87.905227,"(41.976290414, -87.905227221)"
1,10801137,JA100016,12/31/2016 11:58:00 PM,0000X W 113TH PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,RESIDENCE,False,False,522,5.0,34.0,49.0,04B,1178014.0,1829709.0,2016,02/10/2018 03:50:01 PM,41.688033,-87.623931,"(41.688033246, -87.623931468)"
2,10801110,JA100027,12/31/2016 11:55:00 PM,030XX N LINCOLN AVE,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,RESIDENCE,True,False,1932,19.0,32.0,6.0,22,1166154.0,1920300.0,2016,01/07/2017 03:56:13 PM,41.936885,-87.664770,"(41.936884881, -87.66476981)"
3,10802006,JA100012,12/31/2016 11:55:00 PM,0000X E WACKER PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,HOTEL/MOTEL,False,True,111,1.0,42.0,32.0,08B,1176964.0,1902140.0,2016,02/10/2018 03:50:01 PM,41.886815,-87.625593,"(41.886814897, -87.625592678)"
4,10801865,JA100839,12/31/2016 11:54:00 PM,078XX S INDIANA AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,True,623,6.0,6.0,69.0,14,1178949.0,1853139.0,2016,02/10/2018 03:50:01 PM,41.752307,-87.619798,"(41.752307019, -87.619797619)"

In [7]:
df['Date'] = pd.to_datetime(df['Date'])

C:\Users\ADMIN\AppData\Local\Temp\ipykernel_6492\2394721818.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date'] = pd.to_datetime(df['Date'])

In [ ]:
df['Date'].dtype

dtype('<M8[ns]')

In [9]:
df = df.sort_values(by='Date', ascending=False).reset_index(drop=True)

In [10]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10819224,JA119772,2016-12-31 23:59:00,100XX W OHARE ST,0810,THEFT,OVER $500,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,False,False,1651,16.0,41.0,76.0,06,1100658.0,1934241.0,2016,02/10/2018 03:50:01 PM,41.976290,-87.905227,"(41.976290414, -87.905227221)"
1,10801137,JA100016,2016-12-31 23:58:00,0000X W 113TH PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,RESIDENCE,False,False,522,5.0,34.0,49.0,04B,1178014.0,1829709.0,2016,02/10/2018 03:50:01 PM,41.688033,-87.623931,"(41.688033246, -87.623931468)"
2,10801110,JA100027,2016-12-31 23:55:00,030XX N LINCOLN AVE,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,RESIDENCE,True,False,1932,19.0,32.0,6.0,22,1166154.0,1920300.0,2016,01/07/2017 03:56:13 PM,41.936885,-87.664770,"(41.936884881, -87.66476981)"
3,10802006,JA100012,2016-12-31 23:55:00,0000X E WACKER PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,HOTEL/MOTEL,False,True,111,1.0,42.0,32.0,08B,1176964.0,1902140.0,2016,02/10/2018 03:50:01 PM,41.886815,-87.625593,"(41.886814897, -87.625592678)"
4,10801865,JA100839,2016-12-31 23:54:00,078XX S INDIANA AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,True,623,6.0,6.0,69.0,14,1178949.0,1853139.0,2016,02/10/2018 03:50:01 PM,41.752307,-87.619798,"(41.752307019, -87.619797619)"

In [11]:
df.tail()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
2997476,6025491,HP128861,2008-01-01,037XX S CALIFORNIA AVE,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,913,9.0,12.0,58.0,08A,1158320.0,1879508.0,2008,09/23/2025 03:41:47 PM,41.825112,-87.694676,"(41.825111827, -87.694676477)"
2997477,8565120,HV238777,2008-01-01,052XX S WINCHESTER AVE,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,RESIDENCE,False,False,932,9.0,16.0,61.0,17,NaN,NaN,2008,09/23/2025 03:41:47 PM,NaN,NaN,NaN
2997478,7872854,HT103682,2008-01-01,099XX S COMMERCIAL AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,431,4.0,10.0,51.0,06,NaN,NaN,2008,08/17/2015 03:03:40 PM,NaN,NaN,NaN
2997479,6139616,HP231701,2008-01-01,064XX N TROY ST,2825,OTHER OFFENSE,HARASSMENT BY TELEPHONE,RESIDENCE,False,False,2412,24.0,50.0,2.0,26,1154170.0,1942588.0,2008,02/10/2018 03:50:01 PM,41.998293,-87.708215,"(41.998292507, -87.708215117)"
2997480,8645095,HT654575,2008-01-01,060XX S TRIPP AVE,1752,OFFENSE INVOLVING CHILDREN,AGG CRIM SEX ABUSE FAM MEMBER,APARTMENT,False,True,813,8.0,13.0,65.0,17,NaN,NaN,2008,09/23/2025 03:41:47 PM,NaN,NaN,NaN

In [12]:
df_sampled = df.head(500000)

In [13]:
# After sampling the data got unsorted so we need to sort again
df_sampled.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10819224,JA119772,2016-12-31 23:59:00,100XX W OHARE ST,0810,THEFT,OVER $500,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,False,False,1651,16.0,41.0,76.0,06,1100658.0,1934241.0,2016,02/10/2018 03:50:01 PM,41.976290,-87.905227,"(41.976290414, -87.905227221)"
1,10801137,JA100016,2016-12-31 23:58:00,0000X W 113TH PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,RESIDENCE,False,False,522,5.0,34.0,49.0,04B,1178014.0,1829709.0,2016,02/10/2018 03:50:01 PM,41.688033,-87.623931,"(41.688033246, -87.623931468)"
2,10801110,JA100027,2016-12-31 23:55:00,030XX N LINCOLN AVE,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,RESIDENCE,True,False,1932,19.0,32.0,6.0,22,1166154.0,1920300.0,2016,01/07/2017 03:56:13 PM,41.936885,-87.664770,"(41.936884881, -87.66476981)"
3,10802006,JA100012,2016-12-31 23:55:00,0000X E WACKER PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,HOTEL/MOTEL,False,True,111,1.0,42.0,32.0,08B,1176964.0,1902140.0,2016,02/10/2018 03:50:01 PM,41.886815,-87.625593,"(41.886814897, -87.625592678)"
4,10801865,JA100839,2016-12-31 23:54:00,078XX S INDIANA AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,True,623,6.0,6.0,69.0,14,1178949.0,1853139.0,2016,02/10/2018 03:50:01 PM,41.752307,-87.619798,"(41.752307019, -87.619797619)"

In [14]:
df_sampled.tail()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
499995,9972945,HY162462,2015-02-24 16:00:00,023XX S MICHIGAN AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,STREET,False,False,131,1.0,2.0,33.0,14,1177583.0,1888663.0,2015,02/10/2018 03:50:01 PM,41.849819,-87.623729,"(41.849819162, -87.623728682)"
499996,9977167,HY166189,2015-02-24 16:00:00,001XX N CANAL ST,2826,OTHER OFFENSE,HARASSMENT BY ELECTRONIC MEANS,FACTORY/MANUFACTURING BUILDING,False,False,121,1.0,42.0,28.0,26,1173108.0,1900956.0,2015,02/10/2018 03:50:01 PM,41.883652,-87.639788,"(41.883652324, -87.639787936)"
499997,9989839,HY179871,2015-02-24 16:00:00,051XX S UNION AVE,0890,THEFT,FROM BUILDING,RESIDENCE,False,False,935,9.0,3.0,61.0,06,1172510.0,1870765.0,2015,02/10/2018 03:50:01 PM,41.800819,-87.642875,"(41.800818923, -87.642875079)"
499998,9972948,HY162473,2015-02-24 16:00:00,064XX S EBERHART AVE,0820,THEFT,$500 AND UNDER,APARTMENT,False,False,312,3.0,20.0,42.0,06,1180684.0,1862500.0,2015,02/10/2018 03:50:01 PM,41.777955,-87.613152,"(41.777954914, -87.613152431)"
499999,9972999,HY162512,2015-02-24 15:57:00,115XX S WENTWORTH AVE,2024,NARCOTICS,POSS: HEROIN(WHITE),STREET,True,False,522,5.0,34.0,53.0,18,1177007.0,1828325.0,2015,02/10/2018 03:50:01 PM,41.684258,-87.627659,"(41.684258039, -87.627659494)"

In [15]:
df_sampled.dtypes

ID                               int64
Case Number                     object
Date                    datetime64[ns]
Block                           object
IUCR                            object
Primary Type                    object
Description                     object
Location Description            object
Arrest                            bool
Domestic                          bool
Beat                             int64
District                       float64
Ward                           float64
Community Area                 float64
FBI Code                        object
X Coordinate                   float64
Y Coordinate                   float64
Year                             int64
Updated On                      object
Latitude                       float64
Longitude                      float64
Location                        object
dtype: object

In [16]:
df_sampled['Primary Type'].unique()

array(['THEFT', 'BATTERY', 'LIQUOR LAW VIOLATION', 'CRIMINAL DAMAGE',
       'ROBBERY', 'WEAPONS VIOLATION', 'BURGLARY', 'CRIM SEXUAL ASSAULT',
       'OFFENSE INVOLVING CHILDREN', 'ASSAULT', 'DECEPTIVE PRACTICE',
       'MOTOR VEHICLE THEFT', 'OTHER OFFENSE', 'NARCOTICS',
       'PUBLIC PEACE VIOLATION', 'CRIMINAL TRESPASS', 'HOMICIDE',
       'OBSCENITY', 'SEX OFFENSE', 'INTERFERENCE WITH PUBLIC OFFICER',
       'KIDNAPPING', 'INTIMIDATION', 'ARSON', 'STALKING',
       'CRIMINAL SEXUAL ASSAULT', 'PROSTITUTION',
       'CONCEALED CARRY LICENSE VIOLATION', 'OTHER NARCOTIC VIOLATION',
       'GAMBLING', 'HUMAN TRAFFICKING', 'NON-CRIMINAL',
       'PUBLIC INDECENCY'], dtype=object)

In [17]:
df_sampled['IUCR'].unique()[:30]

array(['0810', '0430', '2250', '0486', '1310', '0460', '031A', '0320',
       '0334', '143A', '0610', '0291', '0820', '0880', '1710', '041A',
       '0620', '051A', '1320', '1156', '0890', '1750', '0910', '2820',
       '2028', '1305', '0470', '502P', '0281', '0497'], dtype=object)

In [18]:
df_sampled.to_csv("sampled_crime_data.csv", index=False)