In [1]:
# Data Cleaning

import pandas as pd
import numpy as np

In [2]:
# Read the Rawfile

df = pd.read_csv("G:/Mohanraj D_OFFICIAL/GUVI (Data Analyst)/Mini-Projects/PatrolIQ/Crimes_dataset.csv")
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10819224,JA119772,12/31/2016 11:59:00 PM,100XX W OHARE ST,0810,THEFT,OVER $500,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,False,False,...,41.0,76.0,06,1100658.0,1934241.0,2016,02/10/2018 03:50:01 PM,41.976290,-87.905227,"(41.976290414, -87.905227221)"
1,10801137,JA100016,12/31/2016 11:58:00 PM,0000X W 113TH PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,RESIDENCE,False,False,...,34.0,49.0,04B,1178014.0,1829709.0,2016,02/10/2018 03:50:01 PM,41.688033,-87.623931,"(41.688033246, -87.623931468)"
2,10801110,JA100027,12/31/2016 11:55:00 PM,030XX N LINCOLN AVE,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,RESIDENCE,True,False,...,32.0,6.0,22,1166154.0,1920300.0,2016,01/07/2017 03:56:13 PM,41.936885,-87.664770,"(41.936884881, -87.66476981)"
3,10802006,JA100012,12/31/2016 11:55:00 PM,0000X E WACKER PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,HOTEL/MOTEL,False,True,...,42.0,32.0,08B,1176964.0,1902140.0,2016,02/10/2018 03:50:01 PM,41.886815,-87.625593,"(41.886814897, -87.625592678)"
4,10801865,JA100839,12/31/2016 11:54:00 PM,078XX S INDIANA AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,True,...,6.0,69.0,14,1178949.0,1853139.0,2016,02/10/2018 03:50:01 PM,41.752307,-87.619798,"(41.752307019, -87.619797619)"

In [4]:
df.shape

(2997481, 22)

In [6]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2997481 entries, 0 to 2997480
Data columns (total 22 columns):
 #   Column                Dtype
---  ------                -----
 0   ID                    int64
 1   Case Number           object
 2   Date                  object
 3   Block                 object
 4   IUCR                  object
 5   Primary Type          object
 6   Description           object
 7   Location Description  object
 8   Arrest                bool
 9   Domestic              bool
 10  Beat                  int64
 11  District              float64
 12  Ward                  float64
 13  Community Area        float64
 14  FBI Code              object
 15  X Coordinate          float64
 16  Y Coordinate          float64
 17  Year                  int64
 18  Updated On            object
 19  Latitude              float64
 20  Longitude             float64
 21  Location              object
dtypes: bool(2), float64(7), int64(3), object(10)
memory usage: 463.1+ MB

In [9]:
df.describe()

,ID,Beat,District,Ward,Community Area,X Coordinate,Y Coordinate,Year,Latitude,Longitude
count,2.997481e+06,2.997481e+06,2.997441e+06,2.997428e+06,2.996523e+06,2.967917e+06,2.967917e+06,2.997481e+06,2.967917e+06,2.967917e+06
mean,8.381699e+06,1.179139e+03,1.131186e+01,2.277186e+01,3.771809e+01,1.164387e+06,1.885377e+06,2.011584e+03,4.184107e+01,-8.767229e+01
std,1.423037e+06,6.997095e+02,6.928554e+00,1.376160e+01,2.154775e+01,1.780182e+04,3.344896e+04,2.570262e+00,9.206944e-02,6.426750e-02
min,4.379000e+03,1.110000e+02,1.000000e+00,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.008000e+03,3.661945e+01,-9.168657e+01
25%,7.199114e+06,6.210000e+02,6.000000e+00,1.000000e+01,2.300000e+01,1.152626e+06,1.858661e+06,2.009000e+03,4.176752e+01,-8.771499e+01
50%,8.363046e+06,1.032000e+03,1.000000e+01,2.200000e+01,3.200000e+01,1.165898e+06,1.890498e+06,2.011000e+03,4.185505e+01,-8.766653e+01
75%,9.571699e+06,1.723000e+03,1.700000e+01,3.400000e+01,5.800000e+01,1.176352e+06,1.909124e+06,2.014000e+03,4.190651e+01,-8.762842e+01
max,1.419398e+07,2.535000e+03,3.100000e+01,5.000000e+01,7.700000e+01,1.205119e+06,1.951573e+06,2.016000e+03,4.202271e+01,-8.752453e+01

In [11]:
df.dtypes

ID                        int64
Case Number              object
Date                     object
Block                    object
IUCR                     object
Primary Type             object
Description              object
Location Description     object
Arrest                     bool
Domestic                   bool
Beat                      int64
District                float64
Ward                    float64
Community Area          float64
FBI Code                 object
X Coordinate            float64
Y Coordinate            float64
Year                      int64
Updated On               object
Latitude                float64
Longitude               float64
Location                 object
dtype: object

In [12]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10819224,JA119772,12/31/2016 11:59:00 PM,100XX W OHARE ST,0810,THEFT,OVER $500,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,False,False,...,41.0,76.0,06,1100658.0,1934241.0,2016,02/10/2018 03:50:01 PM,41.976290,-87.905227,"(41.976290414, -87.905227221)"
1,10801137,JA100016,12/31/2016 11:58:00 PM,0000X W 113TH PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,RESIDENCE,False,False,...,34.0,49.0,04B,1178014.0,1829709.0,2016,02/10/2018 03:50:01 PM,41.688033,-87.623931,"(41.688033246, -87.623931468)"
2,10801110,JA100027,12/31/2016 11:55:00 PM,030XX N LINCOLN AVE,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,RESIDENCE,True,False,...,32.0,6.0,22,1166154.0,1920300.0,2016,01/07/2017 03:56:13 PM,41.936885,-87.664770,"(41.936884881, -87.66476981)"
3,10802006,JA100012,12/31/2016 11:55:00 PM,0000X E WACKER PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,HOTEL/MOTEL,False,True,...,42.0,32.0,08B,1176964.0,1902140.0,2016,02/10/2018 03:50:01 PM,41.886815,-87.625593,"(41.886814897, -87.625592678)"
4,10801865,JA100839,12/31/2016 11:54:00 PM,078XX S INDIANA AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,True,...,6.0,69.0,14,1178949.0,1853139.0,2016,02/10/2018 03:50:01 PM,41.752307,-87.619798,"(41.752307019, -87.619797619)"

In [14]:
# required datetime conversion
df['Date'] = df['Date'].astype('datetime64[ns]')
df['Updated On'] = df['Updated On'].astype('datetime64[ns]')

# integer type conversion
df['ID'] = df['ID'].astype('Int64')
df['Ward'] = df['Ward'].astype('Int64')
df['District'] = df['District'].astype('Int64')
df['Community Area'] = df['Community Area'].astype('Int64')

# categorical conversion

df["Primary Type"] = df["Primary Type"].astype("category", )
df["Description"] = df["Description"].astype("category")
df["Location Description"] = df["Location Description"].astype("category")
df["FBI Code"] = df["FBI Code"].astype("category")
df["Block"] = df["Block"].astype("category")
df["IUCR"] = df["IUCR"].astype("category")

In [15]:
df.isna().sum()

ID                          0
Case Number                 0
Date                        0
Block                       0
IUCR                        0
Primary Type                0
Description                 0
Location Description     3687
Arrest                      0
Domestic                    0
Beat                        0
District                   40
Ward                       53
Community Area            958
FBI Code                    0
X Coordinate            29564
Y Coordinate            29564
Year                        0
Updated On                  0
Latitude                29564
Longitude               29564
Location                29564
dtype: int64

In [18]:
# since null values are less than 5% we are dropping rows with null values

df = df.dropna(subset=["X Coordinate"])
df = df.dropna(subset=["Community Area"])
df = df.dropna(subset=["Location Description"])
df = df.dropna(subset=["District"])
df = df.dropna(subset=["Ward"])

In [19]:
df.isna().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [20]:
df.shape

(2965283, 22)

In [21]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10819224,JA119772,2016-12-31 23:59:00,100XX W OHARE ST,0810,THEFT,OVER $500,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,False,False,...,41,76,06,1100658.0,1934241.0,2016,2018-02-10 15:50:01,41.976290,-87.905227,"(41.976290414, -87.905227221)"
1,10801137,JA100016,2016-12-31 23:58:00,0000X W 113TH PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,RESIDENCE,False,False,...,34,49,04B,1178014.0,1829709.0,2016,2018-02-10 15:50:01,41.688033,-87.623931,"(41.688033246, -87.623931468)"
2,10801110,JA100027,2016-12-31 23:55:00,030XX N LINCOLN AVE,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,RESIDENCE,True,False,...,32,6,22,1166154.0,1920300.0,2016,2017-01-07 15:56:13,41.936885,-87.664770,"(41.936884881, -87.66476981)"
3,10802006,JA100012,2016-12-31 23:55:00,0000X E WACKER PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,HOTEL/MOTEL,False,True,...,42,32,08B,1176964.0,1902140.0,2016,2018-02-10 15:50:01,41.886815,-87.625593,"(41.886814897, -87.625592678)"
4,10801865,JA100839,2016-12-31 23:54:00,078XX S INDIANA AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,True,...,6,69,14,1178949.0,1853139.0,2016,2018-02-10 15:50:01,41.752307,-87.619798,"(41.752307019, -87.619797619)"

In [22]:
df.tail()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
2997475,5991842,HP100804,2008-01-01,017XX N CENTRAL AVE,0810,THEFT,OVER $500,STREET,False,False,...,29,25,06,1138776.0,1911133.0,2008,2018-02-10 15:50:01,41.912271,-87.765612,"(41.912271433, -87.765611802)"
2997476,6042751,HP145523,2008-01-01,044XX S GREENWOOD AVE,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,...,4,39,08A,1184334.0,1875715.0,2008,2025-09-23 15:41:47,41.814133,-87.599358,"(41.814133279, -87.599357934)"
2997477,6169515,HP255428,2008-01-01,063XX S TROY ST,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,15,66,06,1156476.0,1862473.0,2008,2018-02-28 15:56:25,41.778403,-87.701901,"(41.778402881, -87.701900763)"
2997478,6155958,HP244796,2008-01-01,105XX S CALHOUN AVE,0840,THEFT,FINANCIAL ID THEFT: OVER $300,RESIDENCE,False,False,...,10,51,06,1194870.0,1835586.0,2008,2018-02-28 15:56:25,41.703763,-87.562031,"(41.703762876, -87.562031385)"
2997479,6037053,HP139941,2008-01-01,009XX N HOMAN AVE,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,False,...,27,23,08A,1153543.0,1905875.0,2008,2025-09-23 15:41:47,41.897562,-87.711501,"(41.897561962, -87.711501488)"

In [23]:
df['Arrest'].unique()

array([False,  True])

In [25]:
df['IUCR'].unique()[:20]

['0810', '0430', '2250', '0486', '1310', ..., '041A', '0620', '051A', '0910', '0890']
Length: 20
Categories (382, object): ['0110', '0141', '0142', '0261', ..., '5121', '5130', '5131', '5132']

In [26]:
df['Primary Type'].unique()[:20]

['THEFT', 'BATTERY', 'LIQUOR LAW VIOLATION', 'CRIMINAL DAMAGE', 'ROBBERY', ..., 'CRIMINAL TRESPASS', 'HOMICIDE', 'OBSCENITY', 'INTERFERENCE WITH PUBLIC OFFICER', 'KIDNAPPING']
Length: 20
Categories (32, object): ['ARSON', 'ASSAULT', 'BATTERY', 'BURGLARY', ..., 'SEX OFFENSE', 'STALKING', 'THEFT', 'WEAPONS VIOLATION']

In [27]:

df['Community Area'].unique()[:40]

<IntegerArray>
[76, 49,  6, 32, 69, 16, 22, 25, 68, 19, 74, 42, 61, 52, 23, 38, 20,  8, 53,
 58, 46, 71, 15, 40, 33, 24, 67, 28, 35, 73, 26, 51, 14, 66, 44, 60, 77, 27,
 43, 31]
Length: 40, dtype: Int64

In [28]:
df['FBI Code'].unique()

['06', '04B', '22', '08B', '14', ..., '13', '16', '12', '19', '01B']
Length: 26
Categories (26, object): ['01A', '01B', '02', '03', ..., '20', '22', '24', '26']

In [29]:
df['ID'].unique()

<IntegerArray>
[10819224, 10801137, 10801110, 10802006, 10801865, 10802735, 10801291,
 10801171, 10801143, 10803002,
 ...
  6329378,  6018863,  5994185,  6199837,  6542518,  5991842,  6042751,
  6169515,  6155958,  6037053]
Length: 2965283, dtype: Int64

In [31]:
df[df['Case Number'].duplicated(keep=False)]

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
4162,23047,HZ564892,2016-12-25 22:20:00,086XX S MARYLAND AVE,0110,HOMICIDE,FIRST DEGREE MURDER,PORCH,False,False,...,8,44,01A,1183405.0,1847810.0,2016,2022-09-19 15:41:05,41.737581,-87.603634,"(41.7375811, -87.603634068)"
4196,23046,HZ564892,2016-12-25 21:19:00,086XX S MARYLAND AVE,0110,HOMICIDE,FIRST DEGREE MURDER,PORCH,False,False,...,8,44,01A,1183405.0,1847810.0,2016,2022-09-01 15:42:17,41.737581,-87.603634,"(41.7375811, -87.603634068)"
5224,23035,HZ563253,2016-12-23 23:44:00,005XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,ALLEY,True,False,...,37,25,01A,1141599.0,1903227.0,2016,2022-09-19 15:41:05,41.890525,-87.755436,"(41.890524711, -87.755436387)"
5241,23034,HZ563253,2016-12-23 23:19:00,005XX N LARAMIE AVE,0110,HOMICIDE,FIRST DEGREE MURDER,ALLEY,True,False,...,37,25,01A,1141599.0,1903227.0,2016,2022-09-01 15:42:17,41.890525,-87.755436,"(41.890524711, -87.755436387)"
9586,23029,HZ554936,2016-12-17 13:25:00,001XX W 105TH ST,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,False,...,34,49,01A,1177249.0,1835331.0,2016,2022-09-19 15:41:05,41.703478,-87.626563,"(41.703478083, -87.626563168)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2955795,4415,HP166985,2008-02-09 08:20:00,078XX S WOLCOTT AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,False,False,...,18,71,01A,1165051.0,1852720.0,2008,2022-09-19 15:41:05,41.751462,-87.670740,"(41.751462228, -87.670739627)"
2955796,4414,HP166985,2008-02-09 08:20:00,078XX S WOLCOTT AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,False,False,...,18,71,01A,1165051.0,1852720.0,2008,2022-09-19 15:41:05,41.751462,-87.670740,"(41.751462228, -87.670739627)"
2990944,4382,HP101233,2008-01-06 14:18:00,024XX N MONTICELLO AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,False,...,35,22,01A,1151639.0,1915923.0,2008,2022-09-19 15:41:05,41.925172,-87.718230,"(41.925172259, -87.718230034)"
2995944,4380,HP101233,2008-01-01 16:48:00,024XX N MONTICELLO AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,False,...,35,22,01A,1151639.0,1915923.0,2008,2022-09-19 15:41:05,41.925172,-87.718230,"(41.925172259, -87.718230034)"
2995945,4379,HP101233,2008-01-01 16:48:00,024XX N MONTICELLO AVE,0110,HOMICIDE,FIRST DEGREE MURDER,HOUSE,True,False,...,35,22,01A,1151639.0,1915923.0,2008,2022-09-19 15:41:05,41.925172,-87.718230,"(41.925172259, -87.718230034)"

In [32]:
# drop duplicate rows with the same case number as we are interested in crime ocurence
df = df.drop_duplicates(subset=["Case Number"], keep="first")

In [33]:
df[df['Case Number'].duplicated(keep=False)]

Empty DataFrame
Columns: [ID, Case Number, Date, Block, IUCR, Primary Type, Description, Location Description, Arrest, Domestic, Beat, District, Ward, Community Area, FBI Code, X Coordinate, Y Coordinate, Year, Updated On, Latitude, Longitude, Location]
Index: []

[0 rows x 22 columns]

In [36]:
df.head()

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,10819224,JA119772,2016-12-31 23:59:00,100XX W OHARE ST,0810,THEFT,OVER $500,AIRPORT BUILDING NON-TERMINAL - SECURE AREA,False,False,...,41,76,06,1100658.0,1934241.0,2016,2018-02-10 15:50:01,41.976290,-87.905227,"(41.976290414, -87.905227221)"
1,10801137,JA100016,2016-12-31 23:58:00,0000X W 113TH PL,0430,BATTERY,AGGRAVATED: OTHER DANG WEAPON,RESIDENCE,False,False,...,34,49,04B,1178014.0,1829709.0,2016,2018-02-10 15:50:01,41.688033,-87.623931,"(41.688033246, -87.623931468)"
2,10801110,JA100027,2016-12-31 23:55:00,030XX N LINCOLN AVE,2250,LIQUOR LAW VIOLATION,LIQUOR LICENSE VIOLATION,RESIDENCE,True,False,...,32,6,22,1166154.0,1920300.0,2016,2017-01-07 15:56:13,41.936885,-87.664770,"(41.936884881, -87.66476981)"
3,10802006,JA100012,2016-12-31 23:55:00,0000X E WACKER PL,0486,BATTERY,DOMESTIC BATTERY SIMPLE,HOTEL/MOTEL,False,True,...,42,32,08B,1176964.0,1902140.0,2016,2018-02-10 15:50:01,41.886815,-87.625593,"(41.886814897, -87.625592678)"
4,10801865,JA100839,2016-12-31 23:54:00,078XX S INDIANA AVE,1310,CRIMINAL DAMAGE,TO PROPERTY,RESIDENCE,False,True,...,6,69,14,1178949.0,1853139.0,2016,2018-02-10 15:50:01,41.752307,-87.619798,"(41.752307019, -87.619797619)"

In [38]:
df.dtypes

ID                               Int64
Case Number                     object
Date                    datetime64[ns]
Block                         category
IUCR                          category
Primary Type                  category
Description                   category
Location Description          category
Arrest                            bool
Domestic                          bool
Beat                             int64
District                         Int64
Ward                             Int64
Community Area                   Int64
FBI Code                      category
X Coordinate                   float64
Y Coordinate                   float64
Year                             int64
Updated On              datetime64[ns]
Latitude                       float64
Longitude                      float64
Location                        object
dtype: object

In [39]:
# save the cleaned file as .pkl to conserve column datatypes

df.to_pickle("cleaned_chicago_crime_dataset.pkl")